const metroData = {
    "stations": [
        { "id": 0, "name": "Miyapur", "line": "R", "position": { "x": 5.0, "y": 20 } },
        { "id": 1, "name": "JNTU College", "line": "R", "position": { "x": 8.5, "y": 20 } },
        { "id": 2, "name": "KPHB Colony", "line": "R", "position": { "x": 12.0, "y": 20 } },
        { "id": 3, "name": "Kukatpally", "line": "R", "position": { "x": 15.5, "y": 20 } },
        { "id": 4, "name": "Balanagar", "line": "R", "position": { "x": 19.0, "y": 20 } },
        { "id": 5, "name": "Moosapet", "line": "R", "position": { "x": 22.5, "y": 20 } },
        { "id": 6, "name": "Bharat Nagar", "line": "R", "position": { "x": 26.0, "y": 20 } },
        { "id": 7, "name": "Erragadda", "line": "R", "position": { "x": 29.5, "y": 20 } },
        { "id": 8, "name": "ESI Hospital", "line": "R", "position": { "x": 33.0, "y": 20 } },
        { "id": 9, "name": "S.R Nagar", "line": "R", "position": { "x": 36.5, "y": 20 } },
        { "id": 10, "name": "Ameerpet", "line": "I", "position": { "x": 40.0, "y": 20 } },
        { "id": 11, "name": "Panjagutta", "line": "R", "position": { "x": 43.5, "y": 20 } },
        { "id": 12, "name": "Irrum Manzil", "line": "R", "position": { "x": 47.0, "y": 20 } },
        { "id": 13, "name": "Khairatabad", "line": "R", "position": { "x": 50.5, "y": 20 } },
        { "id": 14, "name": "Lakdi-Ka-Pul", "line": "R", "position": { "x": 54.0, "y": 20 } },
        { "id": 15, "name": "Assembly", "line": "R", "position": { "x": 57.5, "y": 20 } },
        { "id": 16, "name": "Nampally", "line": "R", "position": { "x": 61.0, "y": 20 } },
        { "id": 17, "name": "Gandhi Bhavan", "line": "R", "position": { "x": 64.5, "y": 20 } },
        { "id": 18, "name": "Osmania Medical College", "line": "R", "position": { "x": 68.0, "y": 20 } },
        { "id": 19, "name": "M.G Bus Station", "line": "I", "position": { "x": 71.5, "y": 20 } },
        { "id": 20, "name": "Malakpet", "line": "R", "position": { "x": 75.0, "y": 20 } },
        { "id": 21, "name": "New Market", "line": "R", "position": { "x": 78.5, "y": 20 } },
        { "id": 22, "name": "Musarambagh", "line": "R", "position": { "x": 82.0, "y": 20 } },
        { "id": 23, "name": "Dilsukhnagar", "line": "R", "position": { "x": 85.5, "y": 20 } },
        { "id": 24, "name": "Chaitanyapuri", "line": "R", "position": { "x": 89.0, "y": 20 } },
        { "id": 25, "name": "Victoria Memorial", "line": "R", "position": { "x": 92.5, "y": 20 } },
        { "id": 26, "name": "L B Nagar", "line": "R", "position": { "x": 96.0, "y": 20 } },

        { "id": 27, "name": "Rayadurg", "line": "B", "position": { "x": 40.0, "y": 30 } },
        { "id": 28, "name": "Hitec City", "line": "B", "position": { "x": 37.5, "y": 33 } },
        { "id": 29, "name": "Durgam Cheruvu", "line": "B", "position": { "x": 35.0, "y": 36 } },
        { "id": 30, "name": "Madhapur", "line": "B", "position": { "x": 32.5, "y": 39 } },
        { "id": 31, "name": "Peddamma Gudi", "line": "B", "position": { "x": 30.0, "y": 42 } },
        { "id": 32, "name": "Jubilee Hills Check Post", "line": "B", "position": { "x": 27.5, "y": 45 } },
        { "id": 33, "name": "Road No 5 Jubilee Hills", "line": "B", "position": { "x": 25.0, "y": 48 } },
        { "id": 34, "name": "Yusufguda", "line": "B", "position": { "x": 22.5, "y": 51 } },
        { "id": 35, "name": "Madhura Nagar", "line": "B", "position": { "x": 20.0, "y": 54 } },
        { "id": 36, "name": "Begumpet", "line": "B", "position": { "x": 17.5, "y": 57 } },
        { "id": 37, "name": "Prakash Nagar", "line": "B", "position": { "x": 15.0, "y": 60 } },
        { "id": 38, "name": "Rasoolpura", "line": "B", "position": { "x": 12.5, "y": 63 } },
        { "id": 39, "name": "Paradise", "line": "B", "position": { "x": 10.0, "y": 66 } },
        { "id": 40, "name": "Parade Grounds", "line": "I", "position": { "x": 20.0, "y": 110 } },
        { "id": 41, "name": "Secundrabad east", "line": "B", "position": { "x": 7.5, "y": 69 } },
        { "id": 42, "name": "Mettuguda", "line": "B", "position": { "x": 5.0, "y": 72 } },
        { "id": 43, "name": "Tarnaka", "line": "B", "position": { "x": 2.5, "y": 75 } },
        { "id": 44, "name": "Habsiguda", "line": "B", "position": { "x": 0.0, "y": 78 } },
        { "id": 45, "name": "NGRI", "line": "B", "position": { "x": -2.5, "y": 81 } },
        { "id": 46, "name": "Stadium", "line": "B", "position": { "x": -5.0, "y": 84 } },
        { "id": 47, "name": "Uppal", "line": "B", "position": { "x": -7.5, "y": 87 } },
        { "id": 48, "name": "Nagole", "line": "B", "position": { "x": -10.0, "y": 90 } },

        { "id": 49, "name": "Secundrabad West", "line": "G", "position": { "x": 23.0, "y": 110.0 } },
        { "id": 50, "name": "Gandhi Hospitals", "line": "G", "position": { "x": 26.0, "y": 112.5 } },
        { "id": 51, "name": "Musheerabad", "line": "G", "position": { "x": 29.0, "y": 115.0 } },
        { "id": 52, "name": "RTC X Roads", "line": "G", "position": { "x": 32.0, "y": 117.5 } },
        { "id": 53, "name": "Chikkadpally", "line": "G", "position": { "x": 35.0, "y": 120.0 } },
        { "id": 54, "name": "Narayanaguda", "line": "G", "position": { "x": 38.0, "y": 122.5 } },
        { "id": 55, "name": "Sultan Bazaar", "line": "G", "position": { "x": 41.0, "y": 125.0 } }
    ],
    "connections": [] // keep your original connection data here
};
