const metroData = {
    stations: [
        { id: 0, name: "Miyapur", line: "R" },
        { id: 1, name: "JNTU College", line: "R" },
        { id: 2, name: "KPHB Colony", line: "R" },
        { id: 3, name: "Kukatpally", line: "R" },
        { id: 4, name: "Balanagar", line: "R" },
        { id: 5, name: "Moosapet", line: "R" },
        { id: 6, name: "Bharat Nagar", line: "R" },
        { id: 7, name: "Erragadda", line: "R" },
        { id: 8, name: "ESI Hospital", line: "R" },
        { id: 9, name: "S.R Nagar", line: "R" },
        { id: 10, name: "Ameerpet", line: "I" },
        { id: 11, name: "Panjagutta", line: "R" },
        { id: 12, name: "Irrum Manzil", line: "R" },
        { id: 13, name: "Khairatabad", line: "R" },
        { id: 14, name: "Lakdi-Ka-Pul", line: "R" },
        { id: 15, name: "Assembly", line: "R" },
        { id: 16, name: "Nampally", line: "R" },
        { id: 17, name: "Gandhi Bhavan", line: "R" },
        { id: 18, name: "Osmania Medical College", line: "R" },
        { id: 19, name: "M.G Bus Station", line: "I" },
        { id: 20, name: "Malakpet", line: "R" },
        { id: 21, name: "New Market", line: "R" },
        { id: 22, name: "Musarambagh", line: "R" },
        { id: 23, name: "Dilsukhnagar", line: "R" },
        { id: 24, name: "Chaitanyapuri", line: "R" },
        { id: 25, name: "Victoria Memorial", line: "R" },
        { id: 26, name: "L B Nagar", line: "R" },
        { id: 27, name: "Rayadurg", line: "B" },
        { id: 28, name: "Hitec City", line: "B" },
        { id: 29, name: "Durgam Cheruvu", line: "B" },
        { id: 30, name: "Madhapur", line: "B" },
        { id: 31, name: "Peddamma Gudi", line: "B" },
        { id: 32, name: "Jubilee Hills Check Post", line: "B" },
        { id: 33, name: "Road No 5 Jubilee Hills", line: "B" },
        { id: 34, name: "Yusufguda", line: "B" },
        { id: 35, name: "Madhura Nagar", line: "B" },
        { id: 36, name: "Begumpet", line: "B" },
        { id: 37, name: "Prakash Nagar", line: "B" },
        { id: 38, name: "Rasoolpura", line: "B" },
        { id: 39, name: "Paradise", line: "B" },
        { id: 40, name: "Parade Grounds", line: "I" },
        { id: 41, name: "Secundrabad east", line: "B" },
        { id: 42, name: "Mettuguda", line: "B" },
        { id: 43, name: "Tarnaka", line: "B" },
        { id: 44, name: "Habsiguda", line: "B" },
        { id: 45, name: "NGRI", line: "B" },
        { id: 46, name: "Stadium", line: "B" },
        { id: 47, name: "Uppal", line: "B" },
        { id: 48, name: "Nagole", line: "B" },
        { id: 49, name: "Secundrabad West", line: "G" },
        { id: 50, name: "Gandhi Hospitals", line: "G" },
        { id: 51, name: "Musheerabad", line: "G" },
        { id: 52, name: "RTC X Roads", line: "G" },
        { id: 53, name: "Chikkadpally", line: "G" },
        { id: 54, name: "Narayanaguda", line: "G" },
        { id: 55, name: "Sultan Bazaar", line: "G" }
    ],
    connections: [
        { from: 0, to: 1, distance: 1.8, time: 3 },
        { from: 1, to: 2, distance: 1.5, time: 3 },
        { from: 2, to: 3, distance: 1.5, time: 3 },
        { from: 3, to: 4, distance: 1.4, time: 2 },
        { from: 4, to: 5, distance: 0.7, time: 2 },
        { from: 5, to: 6, distance: 1.0, time: 2 },
        { from: 6, to: 7, distance: 0.8, time: 2 },
        { from: 7, to: 8, distance: 1.2, time: 3 },
        { from: 8, to: 9, distance: 0.7, time: 2 },
        { from: 9, to: 10, distance: 0.7, time: 1 },
        { from: 10, to: 11, distance: 1.1, time: 2 },
        { from: 10, to: 35, distance: 0.7, time: 1 },
        { from: 10, to: 36, distance: 1.6, time: 2 },
        { from: 11, to: 12, distance: 1.0, time: 2 },
        { from: 12, to: 13, distance: 1.2, time: 3 },
        { from: 13, to: 14, distance: 1.1, time: 3 },
        { from: 14, to: 15, distance: 1.0, time: 2 },
        { from: 15, to: 16, distance: 0.7, time: 2 },
        { from: 16, to: 17, distance: 0.8, time: 2 },
        { from: 17, to: 18, distance: 1.0, time: 2 },
        { from: 18, to: 19, distance: 0.6, time: 2 },
        { from: 19, to: 20, distance: 0.9, time: 2 },
        { from: 19, to: 55, distance: 0.7, time: 2 },
        { from: 20, to: 21, distance: 1.1, time: 2 },
        { from: 21, to: 22, distance: 1.0, time: 2 },
        { from: 22, to: 23, distance: 1.5, time: 5 },
        { from: 23, to: 24, distance: 1.1, time: 2 },
        { from: 24, to: 25, distance: 1.2, time: 2 },
        { from: 25, to: 26, distance: 1.4, time: 3 },
        { from: 26, to: 27, distance: 1.4, time: 3 },
        { from: 27, to: 28, distance: 1.5, time: 3 },
        { from: 28, to: 29, distance: 0.8, time: 1 },
        { from: 29, to: 30, distance: 6.9, time: 2 },
        { from: 30, to: 31, distance: 16.9, time: 7 },
        { from: 31, to: 32, distance: 0.9, time: 1 },
        { from: 32, to: 33, distance: 0.6, time: 1 },
        { from: 33, to: 34, distance: 13.4, time: 5 },
        { from: 34, to: 35, distance: 1.4, time: 1 },
        { from: 36, to: 37, distance: 1.4, time: 2 },
        { from: 37, to: 38, distance: 1.1, time: 2 },
        { from: 38, to: 39, distance: 1.0, time: 2 },
        { from: 39, to: 40, distance: 1.2, time: 2 },
        { from: 40, to: 41, distance: 1.6, time: 3 },
        { from: 40, to: 49, distance: 1.3, time: 2 },
        { from: 41, to: 42, distance: 1.9, time: 3 },
        { from: 42, to: 43, distance: 1.3, time: 3 },
        { from: 43, to: 44, distance: 1.6, time: 3 },
        { from: 44, to: 45, distance: 0.9, time: 2 },
        { from: 45, to: 46, distance: 1.2, time: 2 },
        { from: 46, to: 47, distance: 1.1, time: 2 },
        { from: 47, to: 48, distance: 1.0, time: 2 },
        { from: 49, to: 50, distance: 1.2, time: 2 },
        { from: 50, to: 51, distance: 0.9, time: 2 },
        { from: 51, to: 52, distance: 1.2, time: 2 },
        { from: 52, to: 53, distance: 0.8, time: 2 },
        { from: 53, to: 54, distance: 0.9, time: 2 },
        { from: 54, to: 55, distance: 1.3, time: 2 }
    ]
};